process.env.NODE_ENV = 'test'
process.env.PORT = process.env.PORT ?? '3000'
process.env.DATABASE_URL =
  process.env.DATABASE_URL ?? 'postgresql://postgres:postgres@localhost:5432/academy_test'
process.env.JWT_SECRET = process.env.JWT_SECRET ?? 'test-secret-must-be-at-least-thirty-two-chars'
process.env.JWT_REFRESH_SECRET_KEY =
  process.env.JWT_REFRESH_SECRET_KEY ?? 'test-refresh-secret-must-be-at-least-thirty-two-chars'
process.env.JWT_ACCESS_TTL_SECONDS = process.env.JWT_ACCESS_TTL_SECONDS ?? '900'
process.env.JWT_REFRESH_TTL_DAYS = process.env.JWT_REFRESH_TTL_DAYS ?? '30'
process.env.CORS_ORIGINS = process.env.CORS_ORIGINS ?? 'http://localhost:5173'
process.env.PUBLIC_APP_URL = process.env.PUBLIC_APP_URL ?? 'http://localhost:5173'
process.env.EMAIL_PROVIDER = process.env.EMAIL_PROVIDER ?? 'log'
process.env.EMAIL_FROM = process.env.EMAIL_FROM ?? 'Academy Portal <test@example.com>'
process.env.EMAIL_LOG_PATH = process.env.EMAIL_LOG_PATH ?? 'email.test.log'
process.env.SMTP_HOST = process.env.SMTP_HOST ?? 'smtp.example.com'
process.env.SMTP_PORT = process.env.SMTP_PORT ?? '587'
process.env.SMTP_USER = process.env.SMTP_USER ?? ''
process.env.SMTP_PASS = process.env.SMTP_PASS ?? ''
process.env.SMTP_SECURE = process.env.SMTP_SECURE ?? 'false'
process.env.ENABLE_BACKGROUND_WORKERS = process.env.ENABLE_BACKGROUND_WORKERS ?? 'false'
process.env.START_WORKERS_IN_API = process.env.START_WORKERS_IN_API ?? 'true'
process.env.REDIS_URL = process.env.REDIS_URL ?? 'redis://127.0.0.1:6379'
